import Head from "next/head";
import Image from "next/image";
import DebugNavBar from "../components/DebugNavbar";
import Script from "next/script";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>TellR Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>

            <DebugNavBar></DebugNavBar>
            <main className={styles.main}>
                <h1 className="title is-1 tellr-title">TellR</h1>
                <Image
                    src="/images/profile.jpg"
                    height={200}
                    width={200}
                    alt="moa"
                />
            </main>
        </div>
    );
}
