import Head from "next/head";
import Image from "next/image";
import DebugNavBar from "../components/DebugNavbar";
import Script from "next/script";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import { getDiariesForOwner } from "../library/apiCalls";

export default function Home() {
    const STUB_USER = { id: "Benji" };
    const [journalContent, setJournalContent] = useState(null);
    const [user, setUser] = useState(STUB_USER);

    // FIRST LOADING
    useEffect(() => {
        // Chargement journal pour l'utilisateur
        getDiariesForOwner(user.id).then((data) => {
            setJournalContent(...data);
        });

        console.log("journalContent", journalContent);
    }, []);

    // Every refresh
    useEffect(() => {
        if (journalContent) {
            let textarea = document.getElementById("journalContent");
            textarea.scrollTop = textarea.scrollHeight;
        }
    }, journalContent);

    let onTyping = (e) => {
        // TODO CTRL +S => sav en BD
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>TellR Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon.ico" />
            </Head>

            {/* <DebugNavBar></DebugNavBar> */}
            <main className={styles.main}>
                <h1 className={styles.tellrTitle + " title is-1 tellr-title"}>
                    TellR
                </h1>
                {journalContent && (
                    <React.Fragment>
                        {/* <div
                            className={styles.journalBackground}
                            id="journalBackground"
                        ></div> */}
                        <textarea
                            className={
                                styles.journalContent + " textarea is-loading"
                            }
                            id="journalContent"
                            onChange={onTyping}
                            value={journalContent.content}
                        ></textarea>
                    </React.Fragment>
                )}
            </main>
        </div>
    );
}
